using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JVM.Runner {
    public enum OpCodeName {
        bipush,
        d2f,
        d2i,
        d2l,
        dadd,
        dconst_0,
        dconst_1,
        dcmpg,
        dcmpl,
        ddiv,
        dload,
        dload_0,
        dload_1,
        dload_2,
        dload_3,
        dmul,
        drem,
        dstore,
        dstore_0,
        dstore_1,
        dstore_2,
        dstore_3,
        dsub,
        @goto,
        i2d,
        iadd,
        iconst_m1,
        iconst_0,
        iconst_1,
        iconst_2,
        iconst_3,
        iconst_4,
        iconst_5,
        idiv,
        imul,
        isub,
        if_icmple,
        ifeq,
        ifne,
        iload,
        iload_0,
        iload_1,
        iload_2,
        iload_3,
        irem,
        istore,
        istore_0,
        istore_1,
        istore_2,
        istore_3,
        ldc,
        ldc_w,
        ldc2_w,
        nop,
        @return,
        sipush,

        da_oni_nikto_epta_i,
        da_oni_nikto_epta_f,
        da_oni_nikto_epta_d,
        da_oni_nikto_epta_l
    }
}
